version: '3'

services:
  yaml-helm-pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    env_file:
      - .env
    environment:
      - PORT=8080
    volumes:
      # Mount .kube directory for Helm to access Kubernetes config if needed
      - ${HOME}/.kube:/root/.kube:ro
    restart: unless-stopped
