version: '3'

services:
  yaml-helm-pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    env_file:
      - .env
    environment:
      - PORT=4000
      - HOST=0.0.0.0
    volumes:
      # Mount .kube directory for Helm to access Kubernetes config if needed
      - ${HOME}/.kube:/root/.kube:ro
    restart: unless-stopped
